"""Frequency response and steady-state trajectories.

B_omega = (e^{i omega} I - W)^{-1} D
z = B_omega a            (complex steady-state amplitude)
x_t^ss = Re(z e^{i omega t})

Time-average identities (over a full period of omega):
  norm:      (1/T) sum_t || Re(z e^{i omega t}) ||^2 = (1/2) ||z||^2 = (1/2) a^* B^* B a
  variance:  (1/T) sum_t (1/n) || P Re(z e^{i omega t}) ||^2 = (1/(2n)) a^* B^* P B a
  direction: (1/T) sum_t (v^T Re(z e^{i omega t}))^2 = (1/2) |v^T B a|^2 = (1/2) a^* (B^*v)(B^*v)^* a
             — rank-1 PSD Hermitian.
"""

from __future__ import annotations

import numpy as np
from scipy.linalg import eigh


def frequency_response(W: np.ndarray, D: np.ndarray, omega: float) -> np.ndarray:
    n = W.shape[0]
    M = np.exp(1j * omega) * np.eye(n) - W
    return np.linalg.solve(M, D.astype(complex))


def steady_state_amplitude(B: np.ndarray, a: np.ndarray) -> np.ndarray:
    return B @ a


def steady_state_trajectory(
    B: np.ndarray, a: np.ndarray, omega: float, T: int
) -> np.ndarray:
    """Return X with shape (T, n), X[t] = Re(z e^{i omega t}), z = B a."""
    z = B @ a
    t = np.arange(T)
    phases = np.exp(1j * omega * t)
    return np.real(np.outer(phases, z))


def projection_off_consensus(n: int) -> np.ndarray:
    return np.eye(n) - np.ones((n, n)) / n


def _normalize(v: np.ndarray) -> np.ndarray:
    nv = np.linalg.norm(v)
    return v / nv if nv > 0 else v


def functional_over_time(
    X: np.ndarray, objective: str = "norm", v: np.ndarray | None = None
) -> np.ndarray:
    """V_t per the chosen objective.
      norm:      ||X_t||^2
      variance:  (1/n) ||P X_t||^2
      direction: (v^T X_t)^2     (v normalized internally)
    """
    if objective == "norm":
        return np.sum(X * X, axis=1)
    elif objective == "variance":
        n = X.shape[1]
        Xc = X - X.mean(axis=1, keepdims=True)
        return np.sum(Xc * Xc, axis=1) / n
    elif objective == "direction":
        if v is None:
            raise ValueError("direction objective requires v")
        v = _normalize(np.asarray(v, dtype=float).ravel())
        proj = X @ v
        return proj * proj
    else:
        raise ValueError(f"unknown objective: {objective}")


def build_quadratic_form(
    B: np.ndarray, objective: str, n: int, v: np.ndarray | None = None
) -> np.ndarray:
    """Hermitian PSD Q s.t. time-averaged J(a) = a^* Q a.

    norm:      Q = (1/2) B^* B
    variance:  Q = (1/(2n)) B^* P B
    direction: Q = (1/2) (B^* v)(B^* v)^*           (rank 1)
    """
    Bh = B.conj().T
    if objective == "norm":
        Q = 0.5 * (Bh @ B)
    elif objective == "variance":
        P = projection_off_consensus(n)
        Q = (1.0 / (2.0 * n)) * (Bh @ P @ B)
    elif objective == "direction":
        if v is None:
            raise ValueError("direction objective requires v")
        v_n = _normalize(np.asarray(v, dtype=float).ravel())
        u = Bh @ v_n.astype(complex)  # = B^* v
        Q = 0.5 * np.outer(u, u.conj())
    else:
        raise ValueError(f"unknown objective: {objective}")
    Q = 0.5 * (Q + Q.conj().T)
    return Q


# -------------------- centralities --------------------

def source_frequency_centrality(B: np.ndarray) -> np.ndarray:
    """kappa_i = sum_j |B_{ji}| (column 1-norm of |B|).

    Total amplitude of the steady-state oscillatory response generated by a
    unit signal injected at agent i. Matches |H_beta(omega) e_i|_1 from
    thesis Def 6.25 (since |H| = |B|).
    """
    return np.abs(B).sum(axis=0)


def receiver_frequency_centrality(B: np.ndarray) -> np.ndarray:
    """r_j = sum_i |B_{ji}| (row 1-norm of |B|).

    Total amplitude of agent j's response when each other agent receives a
    unit signal.
    """
    return np.abs(B).sum(axis=1)


def eigenvector_centrality_unsigned(A_plus: np.ndarray, A_minus: np.ndarray) -> np.ndarray:
    """Standard (Bonacich) eigenvector centrality of the unsigned underlying graph.

    Uses |A| = A_plus + A_minus and returns its top (Perron) eigenvector,
    sign-fixed and componentwise nonnegative.
    """
    A_abs = np.asarray(A_plus) + np.asarray(A_minus)
    n = A_abs.shape[0]
    if A_abs.sum() == 0:
        return np.ones(n) / np.sqrt(n)
    w, V = eigh(A_abs)
    v = V[:, -1]
    if v.sum() < 0:
        v = -v
    v = np.abs(v)
    nv = np.linalg.norm(v)
    return v / nv if nv > 0 else v
